# Generated by Django 4.2.1 on 2023-10-27 09:19

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('emplyeeIdentficationCode', models.CharField(default='', max_length=50)),
                ('joining_date', models.DateField(default='')),
                ('phone', models.CharField(default='', max_length=15)),
                ('isAdmin', models.BooleanField(default=False)),
                ('casual_leave_days', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('medical_leave_days', models.PositiveIntegerField(default=0)),
                ('lop_leave_days', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(default='', max_length=255)),
                ('profilePic', models.ImageField(null=True, upload_to='profilePic/')),
                ('isReportingManager', models.BooleanField(default=False)),
                ('can_add_employees', models.BooleanField(default=False, null=True)),
                ('can_remove_employees', models.BooleanField(default=False, null=True)),
                ('can_update_employees', models.BooleanField(default=False, null=True)),
                ('can_read_holidays', models.BooleanField(default=False, null=True)),
                ('can_write_holidays', models.BooleanField(default=False, null=True)),
                ('can_create_holidays', models.BooleanField(default=False, null=True)),
                ('can_delete_holidays', models.BooleanField(default=False, null=True)),
                ('can_import_holidays', models.BooleanField(default=False, null=True)),
                ('can_export_holidays', models.BooleanField(default=False, null=True)),
                ('can_acceptOrReject_leaves', models.BooleanField(default=False, null=True)),
                ('can_read_leaves', models.BooleanField(default=False, null=True)),
                ('can_write_leaves', models.BooleanField(default=False, null=True)),
                ('can_create_leaves', models.BooleanField(default=False, null=True)),
                ('can_delete_leaves', models.BooleanField(default=False, null=True)),
                ('can_import_leaves', models.BooleanField(default=False, null=True)),
                ('can_export_leaves', models.BooleanField(default=False, null=True)),
                ('can_read_clients', models.BooleanField(default=False, null=True)),
                ('can_write_clients', models.BooleanField(default=False, null=True)),
                ('can_create_clients', models.BooleanField(default=False, null=True)),
                ('can_delete_clients', models.BooleanField(default=False, null=True)),
                ('can_import_clients', models.BooleanField(default=False, null=True)),
                ('can_export_clients', models.BooleanField(default=False, null=True)),
                ('can_read_projects', models.BooleanField(default=False, null=True)),
                ('can_write_projects', models.BooleanField(default=False, null=True)),
                ('can_create_projects', models.BooleanField(default=False, null=True)),
                ('can_delete_projects', models.BooleanField(default=False, null=True)),
                ('can_import_projects', models.BooleanField(default=False, null=True)),
                ('can_export_projects', models.BooleanField(default=False, null=True)),
                ('can_read_tasks', models.BooleanField(default=False, null=True)),
                ('can_write_tasks', models.BooleanField(default=False, null=True)),
                ('can_create_tasks', models.BooleanField(default=False, null=True)),
                ('can_delete_tasks', models.BooleanField(default=False, null=True)),
                ('can_import_tasks', models.BooleanField(default=False, null=True)),
                ('can_export_tasks', models.BooleanField(default=False, null=True)),
                ('can_read_chats', models.BooleanField(default=False, null=True)),
                ('can_write_chats', models.BooleanField(default=False, null=True)),
                ('can_create_chats', models.BooleanField(default=False, null=True)),
                ('can_delete_chats', models.BooleanField(default=False, null=True)),
                ('can_import_chats', models.BooleanField(default=False, null=True)),
                ('can_export_chats', models.BooleanField(default=False, null=True)),
                ('can_read_assets', models.BooleanField(default=False, null=True)),
                ('can_create_assets', models.BooleanField(default=False, null=True)),
                ('can_write_assets', models.BooleanField(default=False, null=True)),
                ('can_delete_assets', models.BooleanField(default=False, null=True)),
                ('can_import_assets', models.BooleanField(default=False, null=True)),
                ('can_export_assets', models.BooleanField(default=False, null=True)),
                ('can_read_timing_sheets', models.BooleanField(default=False, null=True)),
                ('can_write_timing_sheets', models.BooleanField(default=False, null=True)),
                ('can_create_timing_sheets', models.BooleanField(default=False, null=True)),
                ('can_delete_timing_sheets', models.BooleanField(default=False, null=True)),
                ('can_import_timing_sheets', models.BooleanField(default=False, null=True)),
                ('can_export_timing_sheets', models.BooleanField(default=False, null=True)),
                ('designation', models.CharField(choices=[('des1', 'Designation 01'), ('des2', 'Designation 02'), ('des3', 'Designation 03'), ('des3', 'Designation 04'), ('des3', 'Designation 05'), ('des3', 'Designation 06'), ('des3', 'Designation 07'), ('des3', 'Designation 08'), ('des3', 'Designation 09'), ('des10', 'Designation 10')], default='des1', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('reporting_manager', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManagerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporting_manager_of', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual'), ('medical', 'Medical'), ('lop', 'Loss of Pay')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leavePrecessed', models.BooleanField(default=False)),
                ('processedBy', models.CharField(max_length=100)),
                ('leave_status', models.CharField(choices=[('new', 'New'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='new', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('punch_times', models.JSONField(default=list)),
                ('first_punch_in', models.TimeField(null=True)),
                ('last_punchout', models.TimeField(null=True)),
                ('total_punch_time', models.DurationField(default=datetime.timedelta(0))),
                ('is_holiday', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
